CREATE TABLE IF NOT EXISTS `PREFIX_yuju_product_reports` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `id_task` varchar(64) DEFAULT NULL,
    `report_type` varchar(32) NOT NULL DEFAULT 'gral',
    `trigger` enum('scheduled','manual','webhook') NOT NULL DEFAULT 'manual',
    `status` enum('pending','processing','completed','failed','rejected','limit_reached') NOT NULL DEFAULT 'pending',
    `products_count` int(11) NOT NULL DEFAULT 0,
    `file_path` varchar(512) DEFAULT NULL,
    `file_size` int(11) NOT NULL DEFAULT 0,
    `download_url` text,
    `error_message` text,
    `meta_json` longtext,
    `requested_at` datetime DEFAULT NULL,
    `completed_at` datetime DEFAULT NULL,
    `utc_day` char(10) DEFAULT NULL,
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `unique_id_task` (`id_task`),
    KEY `idx_status` (`status`),
    KEY `idx_utc_day` (`utc_day`),
    KEY `idx_report_type` (`report_type`),
    KEY `idx_requested_at` (`requested_at`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8mb4;
