CREATE TABLE IF NOT EXISTS `PREFIX_yuju_audit_runs` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `trigger` enum('scheduled','manual') NOT NULL DEFAULT 'manual',
    `mode` enum('silent','visual') NOT NULL DEFAULT 'silent',
    `audit_stock` tinyint(1) NOT NULL DEFAULT 1,
    `audit_price` tinyint(1) NOT NULL DEFAULT 1,
    `audit_images` tinyint(1) NOT NULL DEFAULT 0,
    `status` enum('pending','running','paused','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
    `total` int(11) NOT NULL DEFAULT 0,
    `processed` int(11) NOT NULL DEFAULT 0,
    `matched` int(11) NOT NULL DEFAULT 0,
    `diff_found` int(11) NOT NULL DEFAULT 0,
    `fixed` int(11) NOT NULL DEFAULT 0,
    `errors` int(11) NOT NULL DEFAULT 0,
    `not_found` int(11) NOT NULL DEFAULT 0,
    `started_at` datetime DEFAULT NULL,
    `finished_at` datetime DEFAULT NULL,
    `duration_seconds` int(11) DEFAULT NULL,
    `error_message` text,
    `summary_json` longtext,
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_status` (`status`),
    KEY `idx_started_at` (`started_at`),
    KEY `idx_trigger` (`trigger`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PREFIX_yuju_audit_run_details` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `id_audit_run` int(11) NOT NULL,
    `prestashop_product_id` int(11) DEFAULT NULL,
    `yuju_product_id` varchar(255) DEFAULT NULL,
    `sku` varchar(255) DEFAULT NULL,
    `product_name` varchar(512) DEFAULT NULL,
    `ps_stock` int(11) DEFAULT NULL,
    `yuju_stock` int(11) DEFAULT NULL,
    `ps_price` decimal(20,6) DEFAULT NULL,
    `yuju_price` decimal(20,6) DEFAULT NULL,
    `ps_images_count` int(11) DEFAULT NULL,
    `yuju_images_count` int(11) DEFAULT NULL,
    `diffs_json` text,
    `result` enum('matched','diff_fixed','diff_found','diff_error','not_found') NOT NULL DEFAULT 'matched',
    `message` text,
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_audit_run` (`id_audit_run`),
    KEY `idx_result` (`result`),
    KEY `idx_run_result` (`id_audit_run`, `result`),
    KEY `idx_sku` (`sku`),
    KEY `idx_prestashop_product` (`prestashop_product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
